apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-argocd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-argocd
  template:
    metadata:
      labels:
        app: my-app-argocd
    spec:
      containers:
      - name: my-app-container
        image: "$(DOCKER_USERNAME)/my-image:1.0.0"
        ports:
        - containerPort: 80
        env:
        - name: DOCKER_USERNAME
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: DOCKER_USERNAME
