apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-argocd
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-argocd
  template:
    metadata:
      labels:
        app: my-app-argocd
    spec:
      containers:
      - name: my-app-argocd
        image: eladdafna/my-image:1.0.0
        ports:
        - containerPort: 80
