---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: std-apache-pv
  labels:
    type: std-apache-pv
spec:
  storageClassName: std-class
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.8.128 #master node
    path: /home/docker/volume_kubernetes/
...