apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: std-apache-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: std-class
