apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--my-app-argocd
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}--my-app-argocd
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}--my-app-argocd
    spec:
      containers:
      - name: {{ .Release.Name }}--my-app-argocd
        image: {{ .Values.containers.image }}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: {{ .Values.resources.cpu }}
            memory: {{ .Values.resources.memory }}
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}

