---
apiVersion: v1
kind: Service
metadata:
  name: std-apache-svc
spec:
  selector:
    app: my-app-argocd
  ports:
    - protocol: TCP
      port: 88       # port on service
      targetPort: 80  # port in container
      nodePort: 30236  # Specific NodePort you want to assign on ClusterNodes
  type: NodePort      # possible because of 'type: NodePort'
