apiVersion: v1
kind: Service
metadata:
  name: std-apache-svc
spec:
  selector:
    app: {{ .Release.Name }}--my-app-argocd
  ports:
    - protocol: TCP
      port: 88       # port on service
      targetPort: 80  # port in container
  type: ClusterIP
